# Generated by Django 3.2.9 on 2023-05-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0002_auto_20230417_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, db_column='Code', null=True)),
                ('date', models.IntegerField(blank=True, db_column='Date', null=True)),
                ('time', models.IntegerField(blank=True, db_column='Time', null=True)),
                ('recloseprice', models.FloatField(blank=True, db_column='ReClosePrice', null=True)),
                ('matchprice', models.FloatField(blank=True, db_column='MatchPrice', null=True)),
                ('matchvol', models.IntegerField(blank=True, db_column='MatchVol', null=True)),
                ('askvol', models.IntegerField(blank=True, db_column='AskVol', null=True)),
                ('matchincrease', models.IntegerField(blank=True, db_column='MatchIncrease', null=True)),
                ('matchmoney', models.FloatField(blank=True, db_column='Matchmoney', null=True)),
                ('hardenprice', models.FloatField(blank=True, db_column='HardenPrice', null=True)),
                ('limitdownprice', models.FloatField(blank=True, db_column='LimitDownPrice', null=True)),
                ('up', models.FloatField(blank=True, null=True)),
                ('down', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'testdata',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='business_activate',
            field=models.IntegerField(choices=[[0, '已激活'], [1, '未激活']], default=0, verbose_name='业务激活'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='业务截至日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.IntegerField(choices=[[0, '管理员'], [1, '用户']], default=1, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='times',
            field=models.IntegerField(default=0, verbose_name='剩余次数'),
        ),
    ]
