# Generated by Django 3.2.9 on 2023-05-07 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0003_auto_20230507_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testdata',
        ),
    ]
