# Generated by Django 3.2.9 on 2023-05-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0004_delete_testdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthTestdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, db_column='Code', null=True)),
                ('date', models.IntegerField(blank=True, db_column='Date', null=True)),
                ('time', models.IntegerField(blank=True, db_column='Time', null=True)),
                ('recloseprice', models.FloatField(blank=True, db_column='ReClosePrice', null=True)),
                ('matchprice', models.FloatField(blank=True, db_column='MatchPrice', null=True)),
                ('matchvol', models.IntegerField(blank=True, db_column='MatchVol', null=True)),
                ('askvol', models.IntegerField(blank=True, db_column='AskVol', null=True)),
                ('matchincrease', models.IntegerField(blank=True, db_column='MatchIncrease', null=True)),
                ('matchmoney', models.FloatField(blank=True, db_column='Matchmoney', null=True)),
                ('hardenprice', models.FloatField(blank=True, db_column='HardenPrice', null=True)),
                ('limitdownprice', models.FloatField(blank=True, db_column='LimitDownPrice', null=True)),
                ('up', models.FloatField(blank=True, null=True)),
                ('down', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth_testdata',
                'managed': True,
            },
        ),
    ]
