# Generated by Django 3.2.9 on 2023-05-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0005_oauthtestdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtestdata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
