# Generated by Django 3.2.9 on 2023-05-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0006_alter_oauthtestdata_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OauthTestdata',
        ),
    ]
