# Generated by Django 3.2.9 on 2023-05-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0008_oauthtestdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OauthTestdata',
        ),
    ]
