# Generated by Django 3.2.9 on 2023-06-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0043_auto_20230605_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthDate',
            fields=[
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False, verbose_name='日期')),
                ('status', models.IntegerField(choices=[[0, '未存储'], [1, '已存储']], default=0, verbose_name='状态')),
            ],
            options={
                'db_table': 'oauth_date',
                'managed': True,
            },
        ),
    ]
