# Generated by Django 3.2.9 on 2023-06-11 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0046_auto_20230611_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OauthStockData20204',
        ),
        migrations.DeleteModel(
            name='OauthStockData20211',
        ),
        migrations.DeleteModel(
            name='OauthStockData20212',
        ),
        migrations.DeleteModel(
            name='OauthStockData20213',
        ),
        migrations.DeleteModel(
            name='OauthStockData20214',
        ),
        migrations.DeleteModel(
            name='OauthStockData20221',
        ),
        migrations.DeleteModel(
            name='OauthStockData20222',
        ),
        migrations.DeleteModel(
            name='OauthStockData20223',
        ),
        migrations.DeleteModel(
            name='OauthStockData20224',
        ),
        migrations.DeleteModel(
            name='OauthStockData2023_1',
        ),
        migrations.DeleteModel(
            name='OauthStockData2023_2',
        ),
    ]
