# Generated by Django 3.2.9 on 2023-06-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oAuth', '0048_stockdata20204_stockdata20211_stockdata20212_stockdata20213_stockdata20214_stockdata20221_stockdata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockdata20223',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, db_column='Code', null=True)),
                ('date', models.IntegerField(blank=True, db_column='Date', null=True)),
                ('time', models.IntegerField(blank=True, db_column='Time', null=True)),
                ('recloseprice', models.FloatField(blank=True, db_column='ReClosePrice', null=True)),
                ('matchprice', models.FloatField(blank=True, db_column='MatchPrice', null=True)),
                ('matchvol', models.IntegerField(blank=True, db_column='MatchVol', null=True)),
                ('askvol', models.IntegerField(blank=True, db_column='AskVol', null=True)),
                ('matchincrease', models.FloatField(blank=True, db_column='MatchIncrease', null=True)),
                ('matchmoney', models.FloatField(blank=True, db_column='Matchmoney', null=True)),
                ('hardenprice', models.FloatField(blank=True, db_column='HardenPrice', null=True)),
                ('limitdownprice', models.FloatField(blank=True, db_column='LimitDownPrice', null=True)),
                ('up', models.FloatField(blank=True, null=True)),
                ('down', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth_stockdata20223',
            },
        ),
        migrations.CreateModel(
            name='stockdata20224',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, db_column='Code', null=True)),
                ('date', models.IntegerField(blank=True, db_column='Date', null=True)),
                ('time', models.IntegerField(blank=True, db_column='Time', null=True)),
                ('recloseprice', models.FloatField(blank=True, db_column='ReClosePrice', null=True)),
                ('matchprice', models.FloatField(blank=True, db_column='MatchPrice', null=True)),
                ('matchvol', models.IntegerField(blank=True, db_column='MatchVol', null=True)),
                ('askvol', models.IntegerField(blank=True, db_column='AskVol', null=True)),
                ('matchincrease', models.FloatField(blank=True, db_column='MatchIncrease', null=True)),
                ('matchmoney', models.FloatField(blank=True, db_column='Matchmoney', null=True)),
                ('hardenprice', models.FloatField(blank=True, db_column='HardenPrice', null=True)),
                ('limitdownprice', models.FloatField(blank=True, db_column='LimitDownPrice', null=True)),
                ('up', models.FloatField(blank=True, null=True)),
                ('down', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth_stockdata20224',
            },
        ),
        migrations.CreateModel(
            name='stockdata20231',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, db_column='Code', null=True)),
                ('date', models.IntegerField(blank=True, db_column='Date', null=True)),
                ('time', models.IntegerField(blank=True, db_column='Time', null=True)),
                ('recloseprice', models.FloatField(blank=True, db_column='ReClosePrice', null=True)),
                ('matchprice', models.FloatField(blank=True, db_column='MatchPrice', null=True)),
                ('matchvol', models.IntegerField(blank=True, db_column='MatchVol', null=True)),
                ('askvol', models.IntegerField(blank=True, db_column='AskVol', null=True)),
                ('matchincrease', models.FloatField(blank=True, db_column='MatchIncrease', null=True)),
                ('matchmoney', models.FloatField(blank=True, db_column='Matchmoney', null=True)),
                ('hardenprice', models.FloatField(blank=True, db_column='HardenPrice', null=True)),
                ('limitdownprice', models.FloatField(blank=True, db_column='LimitDownPrice', null=True)),
                ('up', models.FloatField(blank=True, null=True)),
                ('down', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth_stockdata20231',
            },
        ),
        migrations.CreateModel(
            name='stockdata20232',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, db_column='Code', null=True)),
                ('date', models.IntegerField(blank=True, db_column='Date', null=True)),
                ('time', models.IntegerField(blank=True, db_column='Time', null=True)),
                ('recloseprice', models.FloatField(blank=True, db_column='ReClosePrice', null=True)),
                ('matchprice', models.FloatField(blank=True, db_column='MatchPrice', null=True)),
                ('matchvol', models.IntegerField(blank=True, db_column='MatchVol', null=True)),
                ('askvol', models.IntegerField(blank=True, db_column='AskVol', null=True)),
                ('matchincrease', models.FloatField(blank=True, db_column='MatchIncrease', null=True)),
                ('matchmoney', models.FloatField(blank=True, db_column='Matchmoney', null=True)),
                ('hardenprice', models.FloatField(blank=True, db_column='HardenPrice', null=True)),
                ('limitdownprice', models.FloatField(blank=True, db_column='LimitDownPrice', null=True)),
                ('up', models.FloatField(blank=True, null=True)),
                ('down', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth_stockdata20232',
            },
        ),
    ]
